In [2]:
import requests
from bs4 import BeautifulSoup

In [4]:
base_url="https://subslikescript.com/movies?page={}"

movie_title=[]
movie_link=[]

for page in range(1,6):
    url=base_url.format(page)
    res=requests.get(url)
    # print(url)
    soup=BeautifulSoup(res.text,"html.parser")
    movie_con =soup.find("ul",class_="scripts-list")
    # print(movie_con)
    movies=movie_con.find_all('a')
    
    for movie in movies:
        #print(movie)
        title=movie.text.strip()
        movie_title.append(title)
        
        link="https://subslikescript.com"+movie['href']
        movie_link.append(link)

In [5]:
movie_title

['The Bee-Deviled Bruin (1949)',
 'More Ants in the Pants (2002)',
 'Eat, Love, London (2024)',
 'Hood Witch (2023)',
 'Doctor Doctor (2024)',
 'The Empty Chair (2025)',
 'Lorna Doone (1934)',
 'Black Out (2012)',
 'Baby Invasion (2024)',
 'Riding the Stallion of a Dream (2010)',
 'The Last Supper (2025)',
 'Little Siberia (2025)',
 'Revelations (2025)',
 'U Want Me 2 Kill Him? (2013)',
 'Deadly Games (2025)',
 'Kejar Mimpi Gaspol! (2023)',
 'From the Heart: The Four Tops 50th Anniversary & Celebration (2005)',
 'The Water-Carrier Is Dead (1977)',
 'Blondie in Society (1941)',
 'Diamantes negros (2013)',
 'The Filmmaker (2018)',
 'Love in the Sand Dunes (1958)',
 'Tombstone-Rashomon (2017)',
 'Escape to Witch Mountain (1975)',
 'Mystery Island: Winner Takes All (2025)',
 'Vampire Circus (1972)',
 'The Unstoppable Man (1961)',
 'Temptations (1949)',
 'The Forest Clown (2025)',
 'House of the Seasons (2023)',
 'Two Gophers from Texas (1948)',
 'The Golden West (2023)',
 'Evelyne (2021)',
 'Trip to Papa (2019)',
 'Mvera (2023)',
 'Dangerous Dan McFoo (1939)',
 'The Colors Within (2024)',
 'Wishmaster 2: Evil Never Dies (1999)',
 'Ash (2025)',
 'Deewaangee (1976)',
 'A Fishy Story (1989)',
 'The Rule of Jenny Pen (2024)',
 'Along Came Daffy (1947)',
 'MMA: Meu Melhor Amigo (2025)',
 'Bwana Devil (1952)',
 'Chuck Billy and the Marvelous Guava Tree (2024)',
 'Chun Tae-Il (2021)',
 'A Kiss Before Dying (1991)',
 "The Legend of Mor'du (2012)",
 'Arouse (2025)',
 'The Least Untrue (2022)',
 'Night of the Zoopocalypse (2024)',
 'The Shrouds (2024)',
 'Batman: The Enemy Within (2017)',
 'Amnesiac (2014)',
 'Dreamers (2025)',
 'Degas and the Dancer (1998)',
 'Blood Star (2024)',
 'Pantry Pirate (1940)',
 '4PM (2024)',
 'Esquizo (1970)',
 'Road to Andalay (1964)',
 'Streamlined Greta Green (1937)',
 'Zero (2024)',
 'When the Ringlights Dim (2025)',
 'Myth of Man (2025)',
 'Lilies Not for Me (2024)',
 'God Save the Queens (2022)',
 'Invasive 2: Getaway (2025)',
 'Helen Razor (2024)',
 'Crushed Wings (2021)',
 'Overgames (2015)',
 'Muallaf (2008)',
 'House of Cards (1968)',
 'Seven Veils (2023)',
 'Blondie for Victory (1942)',
 'Little Remi and Famous Dog Capi (1970)',
 'Horror Story (2013)',
 'The Marching Band (2024)',
 'Harbin (2024)',
 'Sweet Skin (1963)',
 'Hantu Pohon Pisang (2022)',
 'I Kissed a Vampire (2010)',
 'The Monkey (2025)',
 'Fright (2024)',
 'Little Tornadoes (2021)',
 'Dalej jazda! (2024)',
 'Private Information (1952)',
 'House Broken (2010)',
 "Hearts Around the Table: Jenna's First Love (2025)",
 'The World Will Tremble (2025)',
 'Immortality (1998)',
 'Holiday for Drumsticks (1949)',
 'We Found Something (2022)',
 'Livestream (2025)',
 "Pluto's Playmate (1941)",
 "So's Your Uncle (1943)",
 'The Mandarin Mystery (1936)',
 'In Fast Company (1946)',
 'Jinx Money (1948)',
 'Hard Boiled Mahoney (1947)',
 'Girl on the Run (1953)',
 'Dragnet (1947)',
 'Franco Building with Jonathan Meades (2019)',
 'To Die Alone (2024)',
 'Tendaberry (2024)',
 'Seneca (2023)',
 'Invader (2024)',
 'Cannibal Mukbang (2023)',
 'Love from Mother Only (2003)',
 'Odd Girl (2019)',
 'The Kingdom (2024)',
 'Like Friends (2025)',
 'Fixation (2017)',
 'Release (2017)',
 'Hands That Bind (2021)',
 'Vil & Misérable (2024)',
 'Influencer Girl (2024)',
 'Arizona Mahoney (1936)',
 'The Arizona Raiders (1936)',
 'Buona Sera, Mrs. Campbell (1968)',
 'Air Devils (1938)',
 'Isle of Destiny (1940)',
 'The Hike (2011)',
 "L'amour du monde (2023)",
 'One by One (2024)',
 'A Bride for Henry (1937)',
 'Atlantic Flight (1937)',
 'I Am a Criminal (1938)',
 'The Ghost and the Guest (1943)',
 'The Law Commands (1937)',
 'Chelsea Handler: The Feeling (2025)',
 'Con Mum (2025)',
 'The Boy from Macksville (2024)',
 'Silence of Smoke (2023)',
 'Vallatud kurvid (1959)',
 'Backtrack! (1969)',
 'The Eel (1997)',
 'The Concessionaires Must Die! (2017)',
 'The Base (1999)',
 'The Conversations of Donkey and Rabbit (2020)',
 'A Woman Possessed (1958)',
 'Istanbul Trilogy: Muhabbet (2023)',
 'Istanbul Trilogy: Music (2023)',
 'Istanbul Trilogy: Meze (2023)',
 'Loveable (2024)',
 'Lo (2009)',
 'Abigail (2024)',
 'Conclave (2024)',
 'Robot Dreams (2023)']

In [6]:
movie_link

['https://subslikescript.com/movie/The_Bee-Deviled_Bruin-41167',
 'https://subslikescript.com/movie/More_Ants_in_the_Pants-295375',
 'https://subslikescript.com/movie/Eat_Love_London-29311872',
 'https://subslikescript.com/movie/Hood_Witch-27797160',
 'https://subslikescript.com/movie/Doctor_Doctor-29630754',
 'https://subslikescript.com/movie/The_Empty_Chair-24251248',
 'https://subslikescript.com/movie/Lorna_Doone-26649',
 'https://subslikescript.com/movie/Black_Out-2114358',
 'https://subslikescript.com/movie/Baby_Invasion-33029871',
 'https://subslikescript.com/movie/Riding_the_Stallion_of_a_Dream-1794825',
 'https://subslikescript.com/movie/The_Last_Supper-32461003',
 'https://subslikescript.com/movie/Little_Siberia-31828346',
 'https://subslikescript.com/movie/Revelations-32648798',
 'https://subslikescript.com/movie/U_Want_Me_2_Kill_Him-485061',
 'https://subslikescript.com/movie/Deadly_Games-17504980',
 'https://subslikescript.com/movie/Kejar_Mimpi_Gaspol-20765928',
 'https://subslikescript.com/movie/From_the_Heart_The_Four_Tops_50th_Anniversary__Celebration-837147',
 'https://subslikescript.com/movie/The_Water-Carrier_Is_Dead-76663',
 'https://subslikescript.com/movie/Blondie_in_Society-33404',
 'https://subslikescript.com/movie/Diamantes_negros-2362320',
 'https://subslikescript.com/movie/The_Filmmaker-6645798',
 'https://subslikescript.com/movie/Love_in_the_Sand_Dunes-206720',
 'https://subslikescript.com/movie/Tombstone-Rashomon-5669410',
 'https://subslikescript.com/movie/Escape_to_Witch_Mountain-72951',
 'https://subslikescript.com/movie/Mystery_Island_Winner_Takes_All-35660815',
 'https://subslikescript.com/movie/Vampire_Circus-67924',
 'https://subslikescript.com/movie/The_Unstoppable_Man-186657',
 'https://subslikescript.com/movie/Temptations-41626',
 'https://subslikescript.com/movie/The_Forest_Clown-32474968',
 'https://subslikescript.com/movie/House_of_the_Seasons-29579063',
 'https://subslikescript.com/movie/Two_Gophers_from_Texas-40909',
 'https://subslikescript.com/movie/The_Golden_West-26923682',
 'https://subslikescript.com/movie/Evelyne-12771214',
 'https://subslikescript.com/movie/Trip_to_Papa-23032852',
 'https://subslikescript.com/movie/Mvera-29313917',
 'https://subslikescript.com/movie/Dangerous_Dan_McFoo-31206',
 'https://subslikescript.com/movie/The_Colors_Within-23951384',
 'https://subslikescript.com/movie/Wishmaster_2_Evil_Never_Dies-156182',
 'https://subslikescript.com/movie/Ash-17489650',
 'https://subslikescript.com/movie/Deewaangee-293081',
 'https://subslikescript.com/movie/A_Fishy_Story-96989',
 'https://subslikescript.com/movie/The_Rule_of_Jenny_Pen-6874690',
 'https://subslikescript.com/movie/Along_Came_Daffy-39144',
 'https://subslikescript.com/movie/MMA_Meu_Melhor_Amigo-31917839',
 'https://subslikescript.com/movie/Bwana_Devil-44462',
 'https://subslikescript.com/movie/Chuck_Billy_and_the_Marvelous_Guava_Tree-30868610',
 'https://subslikescript.com/movie/Chun_Tae-Il-16159984',
 'https://subslikescript.com/movie/A_Kiss_Before_Dying-102220',
 'https://subslikescript.com/movie/The_Legend_of_Mordu-2565938',
 'https://subslikescript.com/movie/Arouse-36205453',
 'https://subslikescript.com/movie/The_Least_Untrue-16103450',
 'https://subslikescript.com/movie/Night_of_the_Zoopocalypse-29544253',
 'https://subslikescript.com/movie/The_Shrouds-20212786',
 'https://subslikescript.com/movie/Batman_The_Enemy_Within-7170214',
 'https://subslikescript.com/movie/Amnesiac-2837336',
 'https://subslikescript.com/movie/Dreamers-32240190',
 'https://subslikescript.com/movie/Degas_and_the_Dancer-182571',
 'https://subslikescript.com/movie/Blood_Star-28452681',
 'https://subslikescript.com/movie/Pantry_Pirate-32886',
 'https://subslikescript.com/movie/4PM-25383302',
 'https://subslikescript.com/movie/Esquizo-164870',
 'https://subslikescript.com/movie/Road_to_Andalay-58528',
 'https://subslikescript.com/movie/Streamlined_Greta_Green-29614',
 'https://subslikescript.com/movie/Zero-13598080',
 'https://subslikescript.com/movie/When_the_Ringlights_Dim-23560074',
 'https://subslikescript.com/movie/Myth_of_Man-31272547',
 'https://subslikescript.com/movie/Lilies_Not_for_Me-30700695',
 'https://subslikescript.com/movie/God_Save_the_Queens-10880158',
 'https://subslikescript.com/movie/Invasive_2_Getaway-35684711',
 'https://subslikescript.com/movie/Helen_Razor-27487328',
 'https://subslikescript.com/movie/Crushed_Wings-5772078',
 'https://subslikescript.com/movie/Overgames-5245070',
 'https://subslikescript.com/movie/Muallaf-1263797',
 'https://subslikescript.com/movie/House_of_Cards-64448',
 'https://subslikescript.com/movie/Seven_Veils-26671415',
 'https://subslikescript.com/movie/Blondie_for_Victory-34526',
 'https://subslikescript.com/movie/Little_Remi_and_Famous_Dog_Capi-65544',
 'https://subslikescript.com/movie/Horror_Story-3177332',
 'https://subslikescript.com/movie/The_Marching_Band-30327451',
 'https://subslikescript.com/movie/Harbin-23630030',
 'https://subslikescript.com/movie/Sweet_Skin-57536',
 'https://subslikescript.com/movie/Hantu_Pohon_Pisang-21611248',
 'https://subslikescript.com/movie/I_Kissed_a_Vampire-1656179',
 'https://subslikescript.com/movie/The_Monkey-27714946',
 'https://subslikescript.com/movie/Fright-30020955',
 'https://subslikescript.com/movie/Little_Tornadoes-1592581',
 'https://subslikescript.com/movie/Dalej_jazda-34877638',
 'https://subslikescript.com/movie/Private_Information-261917',
 'https://subslikescript.com/movie/House_Broken-1054631',
 'https://subslikescript.com/movie/Hearts_Around_the_Table_Jennas_First_Love-35660830',
 'https://subslikescript.com/movie/The_World_Will_Tremble-26595906',
 'https://subslikescript.com/movie/Immortality-120894',
 'https://subslikescript.com/movie/Holiday_for_Drumsticks-41474',
 'https://subslikescript.com/movie/We_Found_Something-15180492',
 'https://subslikescript.com/movie/Livestream-32221549',
 'https://subslikescript.com/movie/Plutos_Playmate-34034',
 'https://subslikescript.com/movie/Sos_Your_Uncle-36369',
 'https://subslikescript.com/movie/The_Mandarin_Mystery-29207',
 'https://subslikescript.com/movie/In_Fast_Company-38636',
 'https://subslikescript.com/movie/Jinx_Money-40489',
 'https://subslikescript.com/movie/Hard_Boiled_Mahoney-39447',
 'https://subslikescript.com/movie/Girl_on_the_Run-54930',
 'https://subslikescript.com/movie/Dragnet-39339',
 'https://subslikescript.com/movie/Franco_Building_with_Jonathan_Meades-10888768',
 'https://subslikescript.com/movie/To_Die_Alone-8736506',
 'https://subslikescript.com/movie/Tendaberry-30320639',
 'https://subslikescript.com/movie/Seneca-10155748',
 'https://subslikescript.com/movie/Invader-31381322',
 'https://subslikescript.com/movie/Cannibal_Mukbang-27480944',
 'https://subslikescript.com/movie/Love_from_Mother_Only-366170',
 'https://subslikescript.com/movie/Odd_Girl-9843174',
 'https://subslikescript.com/movie/The_Kingdom-32086032',
 'https://subslikescript.com/movie/Like_Friends-35620409',
 'https://subslikescript.com/movie/Fixation-6593714',
 'https://subslikescript.com/movie/Release-5170144',
 'https://subslikescript.com/movie/Hands_That_Bind-9014060',
 'https://subslikescript.com/movie/Vil__Misrable-33320245',
 'https://subslikescript.com/movie/Influencer_Girl-30749092',
 'https://subslikescript.com/movie/Arizona_Mahoney-28584',
 'https://subslikescript.com/movie/The_Arizona_Raiders-27308',
 'https://subslikescript.com/movie/Buona_Sera_Mrs_Campbell-62767',
 'https://subslikescript.com/movie/Air_Devils-29847',
 'https://subslikescript.com/movie/Isle_of_Destiny-32642',
 'https://subslikescript.com/movie/The_Hike-1572194',
 'https://subslikescript.com/movie/Lamour_du_monde-15607898',
 'https://subslikescript.com/movie/One_by_One-28238574',
 'https://subslikescript.com/movie/A_Bride_for_Henry-28662',
 'https://subslikescript.com/movie/Atlantic_Flight-28592',
 'https://subslikescript.com/movie/I_Am_a_Criminal-30253',
 'https://subslikescript.com/movie/The_Ghost_and_the_Guest-35938',
 'https://subslikescript.com/movie/The_Law_Commands-29122',
 'https://subslikescript.com/movie/Chelsea_Handler_The_Feeling-35820235',
 'https://subslikescript.com/movie/Con_Mum-35955855',
 'https://subslikescript.com/movie/The_Boy_from_Macksville-35065154',
 'https://subslikescript.com/movie/Silence_of_Smoke-5653722',
 'https://subslikescript.com/movie/Vallatud_kurvid-142954',
 'https://subslikescript.com/movie/Backtrack-64059',
 'https://subslikescript.com/movie/The_Eel-120408',
 'https://subslikescript.com/movie/The_Concessionaires_Must_Die-3257092',
 'https://subslikescript.com/movie/The_Base-185908',
 'https://subslikescript.com/movie/The_Conversations_of_Donkey_and_Rabbit-15121938',
 'https://subslikescript.com/movie/A_Woman_Possessed-53451',
 'https://subslikescript.com/movie/Istanbul_Trilogy_Muhabbet-29475069',
 'https://subslikescript.com/movie/Istanbul_Trilogy_Music-29474620',
 'https://subslikescript.com/movie/Istanbul_Trilogy_Meze-29474403',
 'https://subslikescript.com/movie/Loveable-26629652',
 'https://subslikescript.com/movie/Lo-1047490',
 'https://subslikescript.com/movie/Abigail-27489557',
 'https://subslikescript.com/movie/Conclave-20215234',
 'https://subslikescript.com/movie/Robot_Dreams-13429870']

In [8]:
import pandas as pd
df=pd.DataFrame({
    "Movie_Title":movie_title,
    "Movie_Link":movie_link
})
df

,Movie_Title,Movie_Link
0,The Bee-Deviled Bruin (1949),https://subslikescript.com/movie/The_Bee-Devil...
1,More Ants in the Pants (2002),https://subslikescript.com/movie/More_Ants_in_...
2,"Eat, Love, London (2024)",https://subslikescript.com/movie/Eat_Love_Lond...
3,Hood Witch (2023),https://subslikescript.com/movie/Hood_Witch-27...
4,Doctor Doctor (2024),https://subslikescript.com/movie/Doctor_Doctor...
...,...,...
145,Loveable (2024),https://subslikescript.com/movie/Loveable-2662...
146,Lo (2009),https://subslikescript.com/movie/Lo-1047490
147,Abigail (2024),https://subslikescript.com/movie/Abigail-27489557
148,Conclave (2024),https://subslikescript.com/movie/Conclave-2021...
149,Robot Dreams (2023),https://subslikescript.com/movie/Robot_Dreams-...

In [29]:
website="30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ Rotten Tomatoes – Movie and TV News.html"
file=open(website,encoding="utf-8")
res=file.read()
# print(res)
titles=[]
ratings=[]
soup=BeautifulSoup(res,"html.parser")
titleS=soup.find_all('div',class_="article_movie_title")
for i in titleS[:30]:
    title=i.text.strip()
    titles.append(title)
# movies=soup.find_all('div',class_="countdown-item")
# for movie in movies[:30]:
#     title=movie.h2.a.text.strip()
#     print(title)
rating=soup.find_all('span',class_="tMeterScore")
for i in rating[:30]:
    print(i.text)
    ratings.append(i.text)

53%
96%
67%
63%
99%
56%
98%
27%
92%
68%
82%
94%
97%
58%
76%
83%
91%
33%
93%
95%
94%
80%
36%
90%
57%

50%
88%
87%
92%

In [30]:
print(len(titles))

30

In [31]:
print(len(ratings))

30

In [34]:
df=pd.DataFrame({
    "Movie_Title":titles,
    "Movie_rating":ratings
})
df

                                          Movie_Title Movie_rating
0        Transformers: Rise of the Beasts (2023)  53%          53%
1     Spider-Man: Across the Spider-Verse (2023)  96%          96%
2                      The Little Mermaid (2023)  67%          67%
3                           The Boogeyman (2023)  63%          63%
4   Are You There God? It's Me, Margaret. (2023)  99%          99%
5                                  Fast X (2023)  56%          56%
6                              BlackBerry (2023)  98%          98%
7                             The Machine (2023)  27%          27%
8                                 Reality (2023)  92%          92%
9                             Flamin' Hot (2023)  68%          68%
10         Guardians of the Galaxy Vol. 3 (2023)  82%          82%
11                              Blue Jean (2022)  94%          94%
12                             Past Lives (2023)  97%          97%
13            The Super Mario Bros. Movie (2023)  58%          58%
14               Avatar: The Way of Water (2022)  76%          76%
15             Guy Ritchie's The Covenant (2023)  83%          83%
16                              Bumblebee (2018)  91%          91%
17                              Nefarious (2023)  33%          33%
18                                   Sisu (2022)  93%          93%
19                   You Hurt My Feelings (2023)  95%          95%
20                   John Wick: Chapter 4 (2023)  94%          94%
21                         Leave No Trace (2022)  80%          80%
22                        About My Father (2023)  36%          36%
23  Dungeons & Dragons: Honor Among Thieves (2023)...          90%
24                           Transformers (2007)  57%          57%
25                                    My Fault (2023)
26                       A Beautiful Life (2023)  50%          50%
27   The Angry Black Girl and Her Monster (2023)  88%          88%
28                                Missing (2023)  87%          87%
29                                    Air (2023)  92%          92%

In [62]:
website="Fact-checks _ PolitiFact.html"
file=open(website,encoding="utf-8")
res=file.read()
names=[]

soup=BeautifulSoup(res,"html.parser")
n=soup.find_all('a',class_="m-statement__name")
for i in n:
    # print(i.text.strip())
    names.append(i.text.strip())

dates=[]
d=soup.find_all('div',class_="m-statement__desc")
for i in d:
    d1=i.text.strip()
    date_on=d1.split('stated on')[1]
    da=date_on.split('in')[0]
    dates.append(da)

statements=[]
s=soup.find_all('div',class_="m-statement__quote")
for i in s:
    #print(i.text.strip())
    statements.append(i.text.strip())

In [63]:
df=pd.DataFrame({
    "Source":names,
    "Date":dates,
    "Statements":statements
})
df

,Source,Date,Statements
0,Kirsten Gillibrand,"March 19, 2026",“President Trump’s tariffs are costing New Yor...
1,Donald Trump,"May 18, 2026","""There's been numerous other occasions over th..."
2,Social Media,"May 19, 2026",“San Diego mosque shooters identified as trans...
3,X posts,"May 14, 2026","Video shows U.S. Rep. Byron Donalds saying, “I..."
4,X posts,"May 6, 2026",An American passenger on the cruise ship invol...
5,Kathy Castor,"April 29, 2026",“Florida is the only state in the nation kicki...
6,Vivek Ramaswamy,"April 24, 2026","In 2020, “Amy Acton called off Ohio’s election..."
7,TikTok posts,"May 8, 2026",Imágenes muestran a personas “infectadas con H...
8,Christine Quinn,"March 5, 2026","“Today, there are more children sleeping in Ne..."
9,Nicholas Langworthy,"March 31, 2026",“The average IRS tax refund is up 11% compared...
10,Donald Trump,"May 7, 2026",Gasoline prices have “come down very substanti...
11,Byron Donalds,"May 4, 2026",Congress passed the 1965 Voting Rights Act bec...
12,Marcy Kaptur,"May 5, 2026",Republicans “want you to pay $1 Billion for a ...
13,Liz Krueger,"March 5, 2026",Proposed data centers in New York state would ...
14,X posts,"May 6, 2026",“California only has ‘enough’ oil and gas supp...
15,Donald Trump,"May 4, 2026","“Consumer confidence is way up."""
16,Sam Sutton,"March 11, 2026","From January 2025 to January 2026, “hate crime..."
17,Fentrice Driskell,"April 29, 2026","“Under federal law, you cannot engage in parti..."
18,Instagram posts,"April 26, 2026",Imagen muestra que “950 inmigrantes derrumbaro...
19,Bernie Sanders,"April 22, 2026",“As a result of the 'Big Beautiful Bill' 15 mi...
20,Tim Scott,"April 26, 2026",“Secret Service remains unpaid” during the par...
21,Pine Tree Results PAC,"April 26, 2026",“Graham Platner blames Maine’s women for getti...
22,Social Media,"April 26, 2026",Video shows “unedited raw security footage” of...
23,Donald Trump,"April 23, 2026",“We are right now producing more oil than Saud...
24,Ron DeSantis,"April 27, 2026","Since the 2020 census, Florida has ""moved from..."
25,Social Media,"April 26, 2026","“Tras el atentado a Trump”, en la cena de corr..."
26,Jay Collins,"April 20, 2026","U.S. Rep. Byron Donalds voted ""against three p..."
27,Robert F. Kennedy Jr.,"April 22, 2026","""There's two ways of calculating percentage"" d..."
28,Joe Rogan,"April 18, 2026","“With one dose of ibogaine, more than 80% of p..."
29,X posts,"April 21, 2026",“Newly released FOIA door logs show that forme...

In [86]:
website="Certified used Mercedes-Benz for sale.html"
file=open(website,encoding="utf-8")
res=file.read()
names=[]
milegae=[]
price=[]
d_name=[]
review=[]
rating=[]

soup=BeautifulSoup(res,"html.parser")
n=soup.find_all('h2',class_="title")
for i in n:
    # print(i.text.strip())
    names.append(i.text.strip())
    
n=soup.find_all('div',class_="mileage")
for i in n:
    # print(i.text.strip())
    milegae.append(i.text.strip())
    
p=soup.find_all('span',class_="primary-price")
for i in p:
    # print(i.text.strip())
    price.append(i.text.strip())
 
p=soup.find_all('div',class_="dealer-name")
for i in p:
    # print(i.text.strip())
    d_name.append(i.text.strip())   

p=soup.find_all(class_="sds-rating__count")
for i in p:
    # print(i.text.strip())
    rating.append(i.text.strip())

p=soup.find_all(class_="sds-rating__link sds-button-link")
for i in p:
    d1=i.text.strip()
    date_on=d1.split('(')[1]
    da=date_on.split('reviews')[0]
    review.append(da)
print(d_name)
print(rating)
print(review)

['Mercedes-Benz of Lynnwood', 'International Autos', 'John Sisson Motors', 'Mercedes-Benz of Santa Rosa', 'Mercedes-Benz of Rochester', 'Benzel-Busch Motor Car', 'Mercedes-Benz of Lancaster', 'Mercedes-Benz of Ontario', 'John Sisson Motors', 'Mercedes-Benz of Augusta', 'Mercedes-Benz of Chicago', 'Mercedes-Benz of South Orlando', 'Contemporary Motor Cars Inc.', 'Mercedes-Benz of Fort Washington', 'Mercedes-Benz of Chicago', 'Mercedes-Benz of Fort Washington', 'Mercedes-Benz of Fort Washington', 'Mercedes-Benz Of Tampa', 'Mercedes-Benz of Walnut Creek', 'Autobahn Motors', 'Bergstrom Luxury on Victory Lane']
['4.4', '4.0', '2.8', '4.7', '4.5', '4.8', '4.8', '2.8', '4.6', '4.8', '4.4', '4.8', '4.5', '4.8', '4.5', '4.5', '4.1', '4.5', '4.8', '4.2']
['130 ', '117 ', '38 ', '30 ', '152 ', '5,283 ', '174 ', '2,016 ', '38 ', '264 ', '1,327 ', '1,388 ', '226 ', '2,788 ', '1,327 ', '2,788 ', '2,788 ', '3,521 ', '1,016 ', '1,000 ', '292 ']

In [73]:
names

['2020 Mercedes-Benz CLA 250 Base 4MATIC',
 '2019 Mercedes-Benz AMG GT 53 Base',
 '2021 Mercedes-Benz AMG GLE 53 Base',
 '2022 Mercedes-Benz AMG CLA 45 Base 4MATIC',
 '2021 Mercedes-Benz AMG GLE 53 Base',
 '2021 Mercedes-Benz E-Class E 450 4MATIC',
 '2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC',
 '2019 Mercedes-Benz S-Class S 560',
 '2021 Mercedes-Benz AMG GLE 53 Base',
 '2021 Mercedes-Benz GLA 250 Base',
 '2022 Mercedes-Benz AMG C 43 Base 4MATIC',
 '2018 Mercedes-Benz AMG C 43 Base 4MATIC',
 '2021 Mercedes-Benz E-Class E 450 4MATIC',
 '2021 Mercedes-Benz S-Class S 580 4MATIC',
 '2022 Mercedes-Benz GLE 450 AWD 4MATIC',
 '2018 Mercedes-Benz GLC 300 Base 4MATIC',
 '2022 Mercedes-Benz AMG GLA 35 Base',
 '2022 Mercedes-Benz GLB 250 Base',
 '2022 Mercedes-Benz S-Class S 500 4MATIC',
 '2020 Mercedes-Benz AMG S 63 Base 4MATIC',
 '2021 Mercedes-Benz GLC 300 Base 4MATIC']

In [76]:
price

['$35,995',
 '$79,995',
 '$80,923',
 '$56,633',
 '$76,995',
 '$76,532',
 '$102,990',
 '$54,580',
 '$76,715',
 '$34,999',
 '$62,991',
 '$39,999',
 '$74,998',
 '$99,822',
 '$73,990',
 '$29,151',
 '$49,736',
 '$42,000',
 '$86,986',
 '$105,997',
 '$37,280']

In [82]:
review

[]

In [ ]:
df=pd.DataFrame({
    "Car_name":names,
    
})